/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as KargoRouteImport } from './routes/_kargo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KargoWhLoaderRouteImport } from './routes/_kargo.wh-loader'
import { Route as KargoMerchantRouteImport } from './routes/_kargo.merchant'
import { Route as KargoDriver2RouteImport } from './routes/_kargo.driver2'
import { Route as KargoDriver1RouteImport } from './routes/_kargo.driver1'
import { Route as KargoCoordOpRouteImport } from './routes/_kargo.coord-op'
import { Route as KargoCoordKuposRouteImport } from './routes/_kargo.coord-kupos'
import { Route as KargoMerchantIndexRouteImport } from './routes/_kargo.merchant.index'
import { Route as KargoCoordOpIndexRouteImport } from './routes/_kargo.coord-op.index'
import { Route as KargoCoordKuposIndexRouteImport } from './routes/_kargo.coord-kupos.index'
import { Route as KargoMerchantSeguimientoRouteImport } from './routes/_kargo.merchant.seguimiento'
import { Route as KargoMerchantReportesRouteImport } from './routes/_kargo.merchant.reportes'
import { Route as KargoMerchantOrdenesRouteImport } from './routes/_kargo.merchant.ordenes'
import { Route as KargoMerchantIncidenciasRouteImport } from './routes/_kargo.merchant.incidencias'
import { Route as KargoMerchantFacturacionRouteImport } from './routes/_kargo.merchant.facturacion'
import { Route as KargoMerchantDocumentosRouteImport } from './routes/_kargo.merchant.documentos'
import { Route as KargoMerchantDevolucionesRouteImport } from './routes/_kargo.merchant.devoluciones'
import { Route as KargoCoordOpMapaRouteImport } from './routes/_kargo.coord-op.mapa'
import { Route as KargoCoordOpLogsRouteImport } from './routes/_kargo.coord-op.logs'
import { Route as KargoCoordOpKanbanRouteImport } from './routes/_kargo.coord-op.kanban'
import { Route as KargoCoordOpIncidenciasRouteImport } from './routes/_kargo.coord-op.incidencias'
import { Route as KargoCoordOpDriversRouteImport } from './routes/_kargo.coord-op.drivers'
import { Route as KargoCoordOpBusesRouteImport } from './routes/_kargo.coord-op.buses'
import { Route as KargoCoordOpAsignacionBusRouteImport } from './routes/_kargo.coord-op.asignacion-bus'
import { Route as KargoCoordOpAsignacionRouteImport } from './routes/_kargo.coord-op.asignacion'
import { Route as KargoCoordOpAlertasRouteImport } from './routes/_kargo.coord-op.alertas'
import { Route as KargoCoordKuposSlasRouteImport } from './routes/_kargo.coord-kupos.slas'
import { Route as KargoCoordKuposOperadoresRouteImport } from './routes/_kargo.coord-kupos.operadores'

const KargoRoute = KargoRouteImport.update({
  id: '/_kargo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KargoWhLoaderRoute = KargoWhLoaderRouteImport.update({
  id: '/wh-loader',
  path: '/wh-loader',
  getParentRoute: () => KargoRoute,
} as any)
const KargoMerchantRoute = KargoMerchantRouteImport.update({
  id: '/merchant',
  path: '/merchant',
  getParentRoute: () => KargoRoute,
} as any)
const KargoDriver2Route = KargoDriver2RouteImport.update({
  id: '/driver2',
  path: '/driver2',
  getParentRoute: () => KargoRoute,
} as any)
const KargoDriver1Route = KargoDriver1RouteImport.update({
  id: '/driver1',
  path: '/driver1',
  getParentRoute: () => KargoRoute,
} as any)
const KargoCoordOpRoute = KargoCoordOpRouteImport.update({
  id: '/coord-op',
  path: '/coord-op',
  getParentRoute: () => KargoRoute,
} as any)
const KargoCoordKuposRoute = KargoCoordKuposRouteImport.update({
  id: '/coord-kupos',
  path: '/coord-kupos',
  getParentRoute: () => KargoRoute,
} as any)
const KargoMerchantIndexRoute = KargoMerchantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KargoMerchantRoute,
} as any)
const KargoCoordOpIndexRoute = KargoCoordOpIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KargoCoordOpRoute,
} as any)
const KargoCoordKuposIndexRoute = KargoCoordKuposIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KargoCoordKuposRoute,
} as any)
const KargoMerchantSeguimientoRoute =
  KargoMerchantSeguimientoRouteImport.update({
    id: '/seguimiento',
    path: '/seguimiento',
    getParentRoute: () => KargoMerchantRoute,
  } as any)
const KargoMerchantReportesRoute = KargoMerchantReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => KargoMerchantRoute,
} as any)
const KargoMerchantOrdenesRoute = KargoMerchantOrdenesRouteImport.update({
  id: '/ordenes',
  path: '/ordenes',
  getParentRoute: () => KargoMerchantRoute,
} as any)
const KargoMerchantIncidenciasRoute =
  KargoMerchantIncidenciasRouteImport.update({
    id: '/incidencias',
    path: '/incidencias',
    getParentRoute: () => KargoMerchantRoute,
  } as any)
const KargoMerchantFacturacionRoute =
  KargoMerchantFacturacionRouteImport.update({
    id: '/facturacion',
    path: '/facturacion',
    getParentRoute: () => KargoMerchantRoute,
  } as any)
const KargoMerchantDocumentosRoute = KargoMerchantDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => KargoMerchantRoute,
} as any)
const KargoMerchantDevolucionesRoute =
  KargoMerchantDevolucionesRouteImport.update({
    id: '/devoluciones',
    path: '/devoluciones',
    getParentRoute: () => KargoMerchantRoute,
  } as any)
const KargoCoordOpMapaRoute = KargoCoordOpMapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => KargoCoordOpRoute,
} as any)
const KargoCoordOpLogsRoute = KargoCoordOpLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => KargoCoordOpRoute,
} as any)
const KargoCoordOpKanbanRoute = KargoCoordOpKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => KargoCoordOpRoute,
} as any)
const KargoCoordOpIncidenciasRoute = KargoCoordOpIncidenciasRouteImport.update({
  id: '/incidencias',
  path: '/incidencias',
  getParentRoute: () => KargoCoordOpRoute,
} as any)
const KargoCoordOpDriversRoute = KargoCoordOpDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => KargoCoordOpRoute,
} as any)
const KargoCoordOpBusesRoute = KargoCoordOpBusesRouteImport.update({
  id: '/buses',
  path: '/buses',
  getParentRoute: () => KargoCoordOpRoute,
} as any)
const KargoCoordOpAsignacionBusRoute =
  KargoCoordOpAsignacionBusRouteImport.update({
    id: '/asignacion-bus',
    path: '/asignacion-bus',
    getParentRoute: () => KargoCoordOpRoute,
  } as any)
const KargoCoordOpAsignacionRoute = KargoCoordOpAsignacionRouteImport.update({
  id: '/asignacion',
  path: '/asignacion',
  getParentRoute: () => KargoCoordOpRoute,
} as any)
const KargoCoordOpAlertasRoute = KargoCoordOpAlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => KargoCoordOpRoute,
} as any)
const KargoCoordKuposSlasRoute = KargoCoordKuposSlasRouteImport.update({
  id: '/slas',
  path: '/slas',
  getParentRoute: () => KargoCoordKuposRoute,
} as any)
const KargoCoordKuposOperadoresRoute =
  KargoCoordKuposOperadoresRouteImport.update({
    id: '/operadores',
    path: '/operadores',
    getParentRoute: () => KargoCoordKuposRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coord-kupos': typeof KargoCoordKuposRouteWithChildren
  '/coord-op': typeof KargoCoordOpRouteWithChildren
  '/driver1': typeof KargoDriver1Route
  '/driver2': typeof KargoDriver2Route
  '/merchant': typeof KargoMerchantRouteWithChildren
  '/wh-loader': typeof KargoWhLoaderRoute
  '/coord-kupos/operadores': typeof KargoCoordKuposOperadoresRoute
  '/coord-kupos/slas': typeof KargoCoordKuposSlasRoute
  '/coord-op/alertas': typeof KargoCoordOpAlertasRoute
  '/coord-op/asignacion': typeof KargoCoordOpAsignacionRoute
  '/coord-op/asignacion-bus': typeof KargoCoordOpAsignacionBusRoute
  '/coord-op/buses': typeof KargoCoordOpBusesRoute
  '/coord-op/drivers': typeof KargoCoordOpDriversRoute
  '/coord-op/incidencias': typeof KargoCoordOpIncidenciasRoute
  '/coord-op/kanban': typeof KargoCoordOpKanbanRoute
  '/coord-op/logs': typeof KargoCoordOpLogsRoute
  '/coord-op/mapa': typeof KargoCoordOpMapaRoute
  '/merchant/devoluciones': typeof KargoMerchantDevolucionesRoute
  '/merchant/documentos': typeof KargoMerchantDocumentosRoute
  '/merchant/facturacion': typeof KargoMerchantFacturacionRoute
  '/merchant/incidencias': typeof KargoMerchantIncidenciasRoute
  '/merchant/ordenes': typeof KargoMerchantOrdenesRoute
  '/merchant/reportes': typeof KargoMerchantReportesRoute
  '/merchant/seguimiento': typeof KargoMerchantSeguimientoRoute
  '/coord-kupos/': typeof KargoCoordKuposIndexRoute
  '/coord-op/': typeof KargoCoordOpIndexRoute
  '/merchant/': typeof KargoMerchantIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/driver1': typeof KargoDriver1Route
  '/driver2': typeof KargoDriver2Route
  '/wh-loader': typeof KargoWhLoaderRoute
  '/coord-kupos/operadores': typeof KargoCoordKuposOperadoresRoute
  '/coord-kupos/slas': typeof KargoCoordKuposSlasRoute
  '/coord-op/alertas': typeof KargoCoordOpAlertasRoute
  '/coord-op/asignacion': typeof KargoCoordOpAsignacionRoute
  '/coord-op/asignacion-bus': typeof KargoCoordOpAsignacionBusRoute
  '/coord-op/buses': typeof KargoCoordOpBusesRoute
  '/coord-op/drivers': typeof KargoCoordOpDriversRoute
  '/coord-op/incidencias': typeof KargoCoordOpIncidenciasRoute
  '/coord-op/kanban': typeof KargoCoordOpKanbanRoute
  '/coord-op/logs': typeof KargoCoordOpLogsRoute
  '/coord-op/mapa': typeof KargoCoordOpMapaRoute
  '/merchant/devoluciones': typeof KargoMerchantDevolucionesRoute
  '/merchant/documentos': typeof KargoMerchantDocumentosRoute
  '/merchant/facturacion': typeof KargoMerchantFacturacionRoute
  '/merchant/incidencias': typeof KargoMerchantIncidenciasRoute
  '/merchant/ordenes': typeof KargoMerchantOrdenesRoute
  '/merchant/reportes': typeof KargoMerchantReportesRoute
  '/merchant/seguimiento': typeof KargoMerchantSeguimientoRoute
  '/coord-kupos': typeof KargoCoordKuposIndexRoute
  '/coord-op': typeof KargoCoordOpIndexRoute
  '/merchant': typeof KargoMerchantIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_kargo': typeof KargoRouteWithChildren
  '/_kargo/coord-kupos': typeof KargoCoordKuposRouteWithChildren
  '/_kargo/coord-op': typeof KargoCoordOpRouteWithChildren
  '/_kargo/driver1': typeof KargoDriver1Route
  '/_kargo/driver2': typeof KargoDriver2Route
  '/_kargo/merchant': typeof KargoMerchantRouteWithChildren
  '/_kargo/wh-loader': typeof KargoWhLoaderRoute
  '/_kargo/coord-kupos/operadores': typeof KargoCoordKuposOperadoresRoute
  '/_kargo/coord-kupos/slas': typeof KargoCoordKuposSlasRoute
  '/_kargo/coord-op/alertas': typeof KargoCoordOpAlertasRoute
  '/_kargo/coord-op/asignacion': typeof KargoCoordOpAsignacionRoute
  '/_kargo/coord-op/asignacion-bus': typeof KargoCoordOpAsignacionBusRoute
  '/_kargo/coord-op/buses': typeof KargoCoordOpBusesRoute
  '/_kargo/coord-op/drivers': typeof KargoCoordOpDriversRoute
  '/_kargo/coord-op/incidencias': typeof KargoCoordOpIncidenciasRoute
  '/_kargo/coord-op/kanban': typeof KargoCoordOpKanbanRoute
  '/_kargo/coord-op/logs': typeof KargoCoordOpLogsRoute
  '/_kargo/coord-op/mapa': typeof KargoCoordOpMapaRoute
  '/_kargo/merchant/devoluciones': typeof KargoMerchantDevolucionesRoute
  '/_kargo/merchant/documentos': typeof KargoMerchantDocumentosRoute
  '/_kargo/merchant/facturacion': typeof KargoMerchantFacturacionRoute
  '/_kargo/merchant/incidencias': typeof KargoMerchantIncidenciasRoute
  '/_kargo/merchant/ordenes': typeof KargoMerchantOrdenesRoute
  '/_kargo/merchant/reportes': typeof KargoMerchantReportesRoute
  '/_kargo/merchant/seguimiento': typeof KargoMerchantSeguimientoRoute
  '/_kargo/coord-kupos/': typeof KargoCoordKuposIndexRoute
  '/_kargo/coord-op/': typeof KargoCoordOpIndexRoute
  '/_kargo/merchant/': typeof KargoMerchantIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/coord-kupos'
    | '/coord-op'
    | '/driver1'
    | '/driver2'
    | '/merchant'
    | '/wh-loader'
    | '/coord-kupos/operadores'
    | '/coord-kupos/slas'
    | '/coord-op/alertas'
    | '/coord-op/asignacion'
    | '/coord-op/asignacion-bus'
    | '/coord-op/buses'
    | '/coord-op/drivers'
    | '/coord-op/incidencias'
    | '/coord-op/kanban'
    | '/coord-op/logs'
    | '/coord-op/mapa'
    | '/merchant/devoluciones'
    | '/merchant/documentos'
    | '/merchant/facturacion'
    | '/merchant/incidencias'
    | '/merchant/ordenes'
    | '/merchant/reportes'
    | '/merchant/seguimiento'
    | '/coord-kupos/'
    | '/coord-op/'
    | '/merchant/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/driver1'
    | '/driver2'
    | '/wh-loader'
    | '/coord-kupos/operadores'
    | '/coord-kupos/slas'
    | '/coord-op/alertas'
    | '/coord-op/asignacion'
    | '/coord-op/asignacion-bus'
    | '/coord-op/buses'
    | '/coord-op/drivers'
    | '/coord-op/incidencias'
    | '/coord-op/kanban'
    | '/coord-op/logs'
    | '/coord-op/mapa'
    | '/merchant/devoluciones'
    | '/merchant/documentos'
    | '/merchant/facturacion'
    | '/merchant/incidencias'
    | '/merchant/ordenes'
    | '/merchant/reportes'
    | '/merchant/seguimiento'
    | '/coord-kupos'
    | '/coord-op'
    | '/merchant'
  id:
    | '__root__'
    | '/'
    | '/_kargo'
    | '/_kargo/coord-kupos'
    | '/_kargo/coord-op'
    | '/_kargo/driver1'
    | '/_kargo/driver2'
    | '/_kargo/merchant'
    | '/_kargo/wh-loader'
    | '/_kargo/coord-kupos/operadores'
    | '/_kargo/coord-kupos/slas'
    | '/_kargo/coord-op/alertas'
    | '/_kargo/coord-op/asignacion'
    | '/_kargo/coord-op/asignacion-bus'
    | '/_kargo/coord-op/buses'
    | '/_kargo/coord-op/drivers'
    | '/_kargo/coord-op/incidencias'
    | '/_kargo/coord-op/kanban'
    | '/_kargo/coord-op/logs'
    | '/_kargo/coord-op/mapa'
    | '/_kargo/merchant/devoluciones'
    | '/_kargo/merchant/documentos'
    | '/_kargo/merchant/facturacion'
    | '/_kargo/merchant/incidencias'
    | '/_kargo/merchant/ordenes'
    | '/_kargo/merchant/reportes'
    | '/_kargo/merchant/seguimiento'
    | '/_kargo/coord-kupos/'
    | '/_kargo/coord-op/'
    | '/_kargo/merchant/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KargoRoute: typeof KargoRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_kargo': {
      id: '/_kargo'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof KargoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_kargo/wh-loader': {
      id: '/_kargo/wh-loader'
      path: '/wh-loader'
      fullPath: '/wh-loader'
      preLoaderRoute: typeof KargoWhLoaderRouteImport
      parentRoute: typeof KargoRoute
    }
    '/_kargo/merchant': {
      id: '/_kargo/merchant'
      path: '/merchant'
      fullPath: '/merchant'
      preLoaderRoute: typeof KargoMerchantRouteImport
      parentRoute: typeof KargoRoute
    }
    '/_kargo/driver2': {
      id: '/_kargo/driver2'
      path: '/driver2'
      fullPath: '/driver2'
      preLoaderRoute: typeof KargoDriver2RouteImport
      parentRoute: typeof KargoRoute
    }
    '/_kargo/driver1': {
      id: '/_kargo/driver1'
      path: '/driver1'
      fullPath: '/driver1'
      preLoaderRoute: typeof KargoDriver1RouteImport
      parentRoute: typeof KargoRoute
    }
    '/_kargo/coord-op': {
      id: '/_kargo/coord-op'
      path: '/coord-op'
      fullPath: '/coord-op'
      preLoaderRoute: typeof KargoCoordOpRouteImport
      parentRoute: typeof KargoRoute
    }
    '/_kargo/coord-kupos': {
      id: '/_kargo/coord-kupos'
      path: '/coord-kupos'
      fullPath: '/coord-kupos'
      preLoaderRoute: typeof KargoCoordKuposRouteImport
      parentRoute: typeof KargoRoute
    }
    '/_kargo/merchant/': {
      id: '/_kargo/merchant/'
      path: '/'
      fullPath: '/merchant/'
      preLoaderRoute: typeof KargoMerchantIndexRouteImport
      parentRoute: typeof KargoMerchantRoute
    }
    '/_kargo/coord-op/': {
      id: '/_kargo/coord-op/'
      path: '/'
      fullPath: '/coord-op/'
      preLoaderRoute: typeof KargoCoordOpIndexRouteImport
      parentRoute: typeof KargoCoordOpRoute
    }
    '/_kargo/coord-kupos/': {
      id: '/_kargo/coord-kupos/'
      path: '/'
      fullPath: '/coord-kupos/'
      preLoaderRoute: typeof KargoCoordKuposIndexRouteImport
      parentRoute: typeof KargoCoordKuposRoute
    }
    '/_kargo/merchant/seguimiento': {
      id: '/_kargo/merchant/seguimiento'
      path: '/seguimiento'
      fullPath: '/merchant/seguimiento'
      preLoaderRoute: typeof KargoMerchantSeguimientoRouteImport
      parentRoute: typeof KargoMerchantRoute
    }
    '/_kargo/merchant/reportes': {
      id: '/_kargo/merchant/reportes'
      path: '/reportes'
      fullPath: '/merchant/reportes'
      preLoaderRoute: typeof KargoMerchantReportesRouteImport
      parentRoute: typeof KargoMerchantRoute
    }
    '/_kargo/merchant/ordenes': {
      id: '/_kargo/merchant/ordenes'
      path: '/ordenes'
      fullPath: '/merchant/ordenes'
      preLoaderRoute: typeof KargoMerchantOrdenesRouteImport
      parentRoute: typeof KargoMerchantRoute
    }
    '/_kargo/merchant/incidencias': {
      id: '/_kargo/merchant/incidencias'
      path: '/incidencias'
      fullPath: '/merchant/incidencias'
      preLoaderRoute: typeof KargoMerchantIncidenciasRouteImport
      parentRoute: typeof KargoMerchantRoute
    }
    '/_kargo/merchant/facturacion': {
      id: '/_kargo/merchant/facturacion'
      path: '/facturacion'
      fullPath: '/merchant/facturacion'
      preLoaderRoute: typeof KargoMerchantFacturacionRouteImport
      parentRoute: typeof KargoMerchantRoute
    }
    '/_kargo/merchant/documentos': {
      id: '/_kargo/merchant/documentos'
      path: '/documentos'
      fullPath: '/merchant/documentos'
      preLoaderRoute: typeof KargoMerchantDocumentosRouteImport
      parentRoute: typeof KargoMerchantRoute
    }
    '/_kargo/merchant/devoluciones': {
      id: '/_kargo/merchant/devoluciones'
      path: '/devoluciones'
      fullPath: '/merchant/devoluciones'
      preLoaderRoute: typeof KargoMerchantDevolucionesRouteImport
      parentRoute: typeof KargoMerchantRoute
    }
    '/_kargo/coord-op/mapa': {
      id: '/_kargo/coord-op/mapa'
      path: '/mapa'
      fullPath: '/coord-op/mapa'
      preLoaderRoute: typeof KargoCoordOpMapaRouteImport
      parentRoute: typeof KargoCoordOpRoute
    }
    '/_kargo/coord-op/logs': {
      id: '/_kargo/coord-op/logs'
      path: '/logs'
      fullPath: '/coord-op/logs'
      preLoaderRoute: typeof KargoCoordOpLogsRouteImport
      parentRoute: typeof KargoCoordOpRoute
    }
    '/_kargo/coord-op/kanban': {
      id: '/_kargo/coord-op/kanban'
      path: '/kanban'
      fullPath: '/coord-op/kanban'
      preLoaderRoute: typeof KargoCoordOpKanbanRouteImport
      parentRoute: typeof KargoCoordOpRoute
    }
    '/_kargo/coord-op/incidencias': {
      id: '/_kargo/coord-op/incidencias'
      path: '/incidencias'
      fullPath: '/coord-op/incidencias'
      preLoaderRoute: typeof KargoCoordOpIncidenciasRouteImport
      parentRoute: typeof KargoCoordOpRoute
    }
    '/_kargo/coord-op/drivers': {
      id: '/_kargo/coord-op/drivers'
      path: '/drivers'
      fullPath: '/coord-op/drivers'
      preLoaderRoute: typeof KargoCoordOpDriversRouteImport
      parentRoute: typeof KargoCoordOpRoute
    }
    '/_kargo/coord-op/buses': {
      id: '/_kargo/coord-op/buses'
      path: '/buses'
      fullPath: '/coord-op/buses'
      preLoaderRoute: typeof KargoCoordOpBusesRouteImport
      parentRoute: typeof KargoCoordOpRoute
    }
    '/_kargo/coord-op/asignacion-bus': {
      id: '/_kargo/coord-op/asignacion-bus'
      path: '/asignacion-bus'
      fullPath: '/coord-op/asignacion-bus'
      preLoaderRoute: typeof KargoCoordOpAsignacionBusRouteImport
      parentRoute: typeof KargoCoordOpRoute
    }
    '/_kargo/coord-op/asignacion': {
      id: '/_kargo/coord-op/asignacion'
      path: '/asignacion'
      fullPath: '/coord-op/asignacion'
      preLoaderRoute: typeof KargoCoordOpAsignacionRouteImport
      parentRoute: typeof KargoCoordOpRoute
    }
    '/_kargo/coord-op/alertas': {
      id: '/_kargo/coord-op/alertas'
      path: '/alertas'
      fullPath: '/coord-op/alertas'
      preLoaderRoute: typeof KargoCoordOpAlertasRouteImport
      parentRoute: typeof KargoCoordOpRoute
    }
    '/_kargo/coord-kupos/slas': {
      id: '/_kargo/coord-kupos/slas'
      path: '/slas'
      fullPath: '/coord-kupos/slas'
      preLoaderRoute: typeof KargoCoordKuposSlasRouteImport
      parentRoute: typeof KargoCoordKuposRoute
    }
    '/_kargo/coord-kupos/operadores': {
      id: '/_kargo/coord-kupos/operadores'
      path: '/operadores'
      fullPath: '/coord-kupos/operadores'
      preLoaderRoute: typeof KargoCoordKuposOperadoresRouteImport
      parentRoute: typeof KargoCoordKuposRoute
    }
  }
}

interface KargoCoordKuposRouteChildren {
  KargoCoordKuposOperadoresRoute: typeof KargoCoordKuposOperadoresRoute
  KargoCoordKuposSlasRoute: typeof KargoCoordKuposSlasRoute
  KargoCoordKuposIndexRoute: typeof KargoCoordKuposIndexRoute
}

const KargoCoordKuposRouteChildren: KargoCoordKuposRouteChildren = {
  KargoCoordKuposOperadoresRoute: KargoCoordKuposOperadoresRoute,
  KargoCoordKuposSlasRoute: KargoCoordKuposSlasRoute,
  KargoCoordKuposIndexRoute: KargoCoordKuposIndexRoute,
}

const KargoCoordKuposRouteWithChildren = KargoCoordKuposRoute._addFileChildren(
  KargoCoordKuposRouteChildren,
)

interface KargoCoordOpRouteChildren {
  KargoCoordOpAlertasRoute: typeof KargoCoordOpAlertasRoute
  KargoCoordOpAsignacionRoute: typeof KargoCoordOpAsignacionRoute
  KargoCoordOpAsignacionBusRoute: typeof KargoCoordOpAsignacionBusRoute
  KargoCoordOpBusesRoute: typeof KargoCoordOpBusesRoute
  KargoCoordOpDriversRoute: typeof KargoCoordOpDriversRoute
  KargoCoordOpIncidenciasRoute: typeof KargoCoordOpIncidenciasRoute
  KargoCoordOpKanbanRoute: typeof KargoCoordOpKanbanRoute
  KargoCoordOpLogsRoute: typeof KargoCoordOpLogsRoute
  KargoCoordOpMapaRoute: typeof KargoCoordOpMapaRoute
  KargoCoordOpIndexRoute: typeof KargoCoordOpIndexRoute
}

const KargoCoordOpRouteChildren: KargoCoordOpRouteChildren = {
  KargoCoordOpAlertasRoute: KargoCoordOpAlertasRoute,
  KargoCoordOpAsignacionRoute: KargoCoordOpAsignacionRoute,
  KargoCoordOpAsignacionBusRoute: KargoCoordOpAsignacionBusRoute,
  KargoCoordOpBusesRoute: KargoCoordOpBusesRoute,
  KargoCoordOpDriversRoute: KargoCoordOpDriversRoute,
  KargoCoordOpIncidenciasRoute: KargoCoordOpIncidenciasRoute,
  KargoCoordOpKanbanRoute: KargoCoordOpKanbanRoute,
  KargoCoordOpLogsRoute: KargoCoordOpLogsRoute,
  KargoCoordOpMapaRoute: KargoCoordOpMapaRoute,
  KargoCoordOpIndexRoute: KargoCoordOpIndexRoute,
}

const KargoCoordOpRouteWithChildren = KargoCoordOpRoute._addFileChildren(
  KargoCoordOpRouteChildren,
)

interface KargoMerchantRouteChildren {
  KargoMerchantDevolucionesRoute: typeof KargoMerchantDevolucionesRoute
  KargoMerchantDocumentosRoute: typeof KargoMerchantDocumentosRoute
  KargoMerchantFacturacionRoute: typeof KargoMerchantFacturacionRoute
  KargoMerchantIncidenciasRoute: typeof KargoMerchantIncidenciasRoute
  KargoMerchantOrdenesRoute: typeof KargoMerchantOrdenesRoute
  KargoMerchantReportesRoute: typeof KargoMerchantReportesRoute
  KargoMerchantSeguimientoRoute: typeof KargoMerchantSeguimientoRoute
  KargoMerchantIndexRoute: typeof KargoMerchantIndexRoute
}

const KargoMerchantRouteChildren: KargoMerchantRouteChildren = {
  KargoMerchantDevolucionesRoute: KargoMerchantDevolucionesRoute,
  KargoMerchantDocumentosRoute: KargoMerchantDocumentosRoute,
  KargoMerchantFacturacionRoute: KargoMerchantFacturacionRoute,
  KargoMerchantIncidenciasRoute: KargoMerchantIncidenciasRoute,
  KargoMerchantOrdenesRoute: KargoMerchantOrdenesRoute,
  KargoMerchantReportesRoute: KargoMerchantReportesRoute,
  KargoMerchantSeguimientoRoute: KargoMerchantSeguimientoRoute,
  KargoMerchantIndexRoute: KargoMerchantIndexRoute,
}

const KargoMerchantRouteWithChildren = KargoMerchantRoute._addFileChildren(
  KargoMerchantRouteChildren,
)

interface KargoRouteChildren {
  KargoCoordKuposRoute: typeof KargoCoordKuposRouteWithChildren
  KargoCoordOpRoute: typeof KargoCoordOpRouteWithChildren
  KargoDriver1Route: typeof KargoDriver1Route
  KargoDriver2Route: typeof KargoDriver2Route
  KargoMerchantRoute: typeof KargoMerchantRouteWithChildren
  KargoWhLoaderRoute: typeof KargoWhLoaderRoute
}

const KargoRouteChildren: KargoRouteChildren = {
  KargoCoordKuposRoute: KargoCoordKuposRouteWithChildren,
  KargoCoordOpRoute: KargoCoordOpRouteWithChildren,
  KargoDriver1Route: KargoDriver1Route,
  KargoDriver2Route: KargoDriver2Route,
  KargoMerchantRoute: KargoMerchantRouteWithChildren,
  KargoWhLoaderRoute: KargoWhLoaderRoute,
}

const KargoRouteWithChildren = KargoRoute._addFileChildren(KargoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KargoRoute: KargoRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
